export type NotificationType = "message" | "event" | "reminder" | "system" | "custom";

export interface Notification {
  id: string;
  title: string;
  content: string;
  type: NotificationType;
  time: string;
  priority: "High" | "Medium" | "Low";
  isRead: boolean;
}

export const dummyNotifications: Notification[] = [
  {
    id: "1",
    title: "New Message",
    content: "You have a new message from Alex regarding the project deadline. Please review it as soon as possible to avoid delays. Let us know if further assistance is needed. Thank you for your attention.",
    type: "message",
    time: "2024-12-27T10:00:00",
    priority: "High",
    isRead: false,
  },
  {
    id: "2",
    title: "Event Reminder",
    content: "Today's team meeting will focus on project milestones and deadlines. Ensure that your tasks are updated in the system. This is crucial for our sprint review next week. Let's strive for maximum efficiency.",
    type: "event",
    time: "2024-12-27T09:30:00",
    priority: "Medium",
    isRead: true,
  },
  {
    id: "3",
    title: "System Update",
    content: "System maintenance is scheduled for tonight between 12 AM and 3 AM. During this time, services will be temporarily unavailable. Kindly save your work beforehand to avoid data loss. We appreciate your patience.",
    type: "system",
    time: "2024-12-27T08:00:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "4",
    title: "Reminder",
    content: "Submit your project report by 5 PM today. This is essential for the upcoming client presentation. Ensure all sections are complete and reviewed. Feel free to reach out for any clarifications.",
    type: "reminder",
    time: "2024-12-27T11:00:00",
    priority: "High",
    isRead: false,
  },
  {
    id: "5",
    title: "Custom Alert",
    content: "Your subscription is set to expire in two days. Renew now to continue enjoying premium benefits without interruption. Exclusive discounts are available for early renewals. Don't miss out!",
    type: "custom",
    time: "2024-12-27T13:00:00",
    priority: "Medium",
    isRead: false,
  },
  {
    id: "6",
    title: "Event Update",
    content: "The Tech Conference venue has been changed to the Grand Hall, City Center. This decision ensures better accommodation for all attendees. Updated schedules and location details are available on the app. Thank you for your cooperation.",
    type: "event",
    time: "2024-12-27T15:00:00",
    priority: "High",
    isRead: false,
  },
  {
    id: "7",
    title: "Message Received",
    content: "John has shared a new file titled 'Project_Plan_v3.pdf' with you. Kindly review it and provide your feedback. This version includes updates based on the last discussion. Let us know if there are any issues.",
    type: "message",
    time: "2024-12-27T16:00:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "8",
    title: "System Upgrade",
    content: "New features have been added to your dashboard for enhanced usability. Explore the updated interface for better insights and faster navigation. We value your feedback, so let us know what you think!",
    type: "system",
    time: "2024-12-27T17:00:00",
    priority: "Medium",
    isRead: false,
  },
  {
    id: "9",
    title: "Custom Alert",
    content: "Your account password was changed successfully. If you did not initiate this change, please contact support immediately. Keeping your account secure is our top priority. Thank you for choosing our services.",
    type: "custom",
    time: "2024-12-27T18:00:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "10",
    title: "Reminder",
    content: "Tomorrow's weekly standup meeting is scheduled for 9 AM. Prepare your updates on the tasks you completed and the challenges you faced. Team collaboration is key to our success. Let’s make this productive.",
    type: "reminder",
    time: "2024-12-27T19:00:00",
    priority: "Medium",
    isRead: true,
  },
  {
    id: "11",
    title: "Event Confirmation",
    content: "Your registration for the Hackathon event is confirmed. Stay tuned for updates regarding the event schedule and rules. Collaborate with peers for innovative solutions. Wishing you all the best!",
    type: "event",
    time: "2024-12-26T09:00:00",
    priority: "High",
    isRead: true,
  },
  {
    id: "12",
    title: "New Message",
    content: "Alex has sent you an invitation to join their project collaboration space. Check your inbox for more details and accept the invitation to get started. Collaboration drives innovation!",
    type: "message",
    time: "2024-12-26T10:30:00",
    priority: "Medium",
    isRead: true,
  },
  {
    id: "13",
    title: "System Alert",
    content: "Unusual login detected from a new device. If this was you, no action is needed. If not, please secure your account immediately. Visit the security section for more information.",
    type: "system",
    time: "2024-12-26T11:00:00",
    priority: "High",
    isRead: false,
  },
  {
    id: "14",
    title: "Reminder",
    content: "Complete your profile to unlock new features on your account. A detailed profile increases visibility for potential collaborations. Take advantage of these opportunities today!",
    type: "reminder",
    time: "2024-12-26T12:00:00",
    priority: "Medium",
    isRead: false,
  },
  {
    id: "15",
    title: "Custom Notification",
    content: "Your feedback has been received and is under review. We appreciate you taking the time to share your thoughts. Enhancing your experience is our top priority. Thank you for your input!",
    type: "custom",
    time: "2024-12-26T13:00:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "16",
    title: "Event Reminder",
    content: "The workshop on advanced data analytics starts at 3 PM today. Ensure you have registered and prepared your materials. Let’s dive into the latest trends in analytics together.",
    type: "event",
    time: "2024-12-26T14:00:00",
    priority: "High",
    isRead: true,
  },
  {
    id: "17",
    title: "Message",
    content: "The team has updated the project timeline to accommodate recent changes. Please review the updated milestones and provide your feedback. Collaboration is key to our success.",
    type: "message",
    time: "2024-12-26T15:30:00",
    priority: "Medium",
    isRead: false,
  },
  {
    id: "18",
    title: "System Notification",
    content: "Your system backup completed successfully last night. Ensure your data is secure and up-to-date. Visit the backup section for more options to protect your files.",
    type: "system",
    time: "2024-12-26T16:00:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "19",
    title: "Reminder",
    content: "Don’t forget your meeting with Sarah at 6 PM today. Prepare the necessary documents and discussion points beforehand. Make the most of this collaborative opportunity.",
    type: "reminder",
    time: "2024-12-26T17:00:00",
    priority: "High",
    isRead: true,
  },
  {
    id: "20",
    title: "Custom Alert",
    content: "You have new insights to review based on your recent activity. These insights are designed to enhance your productivity. Log in to explore personalized recommendations now.",
    type: "custom",
    time: "2024-12-26T18:30:00",
    priority: "Medium",
    isRead: false,
  },
  {
    id: "21",
    title: "New Message",
    content: "Mike has sent a collaboration request for a new project. Review the project details and decide whether to accept the invitation. Collaboration drives innovation.",
    type: "message",
    time: "2024-12-25T10:00:00",
    priority: "High",
    isRead: false,
  },
  {
    id: "22",
    title: "Event Notification",
    content: "A webinar is scheduled for this Thursday on emerging tech trends. Register to secure your spot and gain valuable insights. Stay ahead in your industry!",
    type: "event",
    time: "2024-12-25T11:30:00",
    priority: "Medium",
    isRead: true,
  },
  {
    id: "23",
    title: "System Update",
    content: "Your mobile app has been updated with new features. Explore the enhanced user interface for better functionality. Let us know if you encounter any issues.",
    type: "system",
    time: "2024-12-24T09:00:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "24",
    title: "Reminder",
    content: "Upload all necessary documents by Friday to meet the deadline. Ensure the files are accurate and complete for a smooth review process. Reach out if assistance is needed.",
    type: "reminder",
    time: "2024-12-24T14:00:00",
    priority: "High",
    isRead: false,
  },
  {
    id: "25",
    title: "Custom Notification",
    content: "Your application has been approved! Check your email for additional details. Welcome to the team. We’re excited to have you on board.",
    type: "custom",
    time: "2024-12-23T15:00:00",
    priority: "Medium",
    isRead: false,
  },
  {
    id: "26",
    title: "Event Reminder",
    content: "The team-building activity this weekend is confirmed. Make sure to RSVP and prepare for some fun-filled collaboration. See you there!",
    type: "event",
    time: "2024-12-22T16:00:00",
    priority: "High",
    isRead: true,
  },
  {
    id: "27",
    title: "Message",
    content: "The HR team has shared the payroll update for this month. Review your payslip in the portal and report any discrepancies. Your feedback is important to us.",
    type: "message",
    time: "2024-12-21T11:00:00",
    priority: "Medium",
    isRead: true,
  },
  {
    id: "28",
    title: "System Alert",
    content: "Your password reset request was successful. Ensure your new password is strong and unique. Reach out if you encounter any issues during login.",
    type: "system",
    time: "2024-12-21T12:30:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "29",
    title: "Custom Alert",
    content: "Submit your timesheet by end-of-day today to avoid delays in payroll processing. Visit the portal to complete the submission process efficiently.",
    type: "custom",
    time: "2024-12-20T10:00:00",
    priority: "Low",
    isRead: false,
  },
  {
    id: "30",
    title: "Reminder",
    content: "Plan your tasks for next week to stay ahead of your schedule. Use the task planner for better organization. Let’s make the most of our time.",
    type: "reminder",
    time: "2024-12-19T18:00:00",
    priority: "Medium",
    isRead: true,
  },
  {
    id: "31",
    title: "New Message",
    content: "The latest news updates are available in the portal. Check them out to stay informed about recent developments. Stay connected and updated.",
    type: "message",
    time: "2024-12-18T09:00:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "32",
    title: "Event Alert",
    content: "Sign up for the Annual Summit to be held next month. Explore opportunities to network and grow professionally. Don’t miss this opportunity!",
    type: "event",
    time: "2024-12-16T14:00:00",
    priority: "High",
    isRead: false,
  },
  {
    id: "33",
    title: "System Update",
    content: "Server maintenance completed successfully last night. Your services are now fully operational. Thank you for your understanding during the downtime.",
    type: "system",
    time: "2024-12-15T17:00:00",
    priority: "Medium",
    isRead: true,
  },
  {
    id: "34",
    title: "Reminder",
    content: "Complete your annual review by the end of the month. A detailed review ensures clarity in objectives for the upcoming year. Reach out for assistance if needed.",
    type: "reminder",
    time: "2024-12-12T11:00:00",
    priority: "High",
    isRead: false,
  },
  {
    id: "35",
    title: "Custom Alert",
    content: "Your invoice for last month is ready. Review the details and download it from the billing section. Contact support if you have any questions.",
    type: "custom",
    time: "2024-12-10T13:30:00",
    priority: "Medium",
    isRead: true,
  },
  {
    id: "36",
    title: "Event Update",
    content: "A new speaker has been added to the Tech Conference panel. Visit the event page to learn more about their expertise. We’re excited about their participation!",
    type: "event",
    time: "2024-12-09T16:00:00",
    priority: "Medium",
    isRead: false,
  },
  {
    id: "37",
    title: "Message",
    content: "The finance team has shared the latest budget report. Review the allocations and provide your inputs by the end of the week. Collaboration is vital to achieving our goals.",
    type: "message",
    time: "2024-12-08T15:00:00",
    priority: "High",
    isRead: true,
  },
  {
    id: "38",
    title: "System Notification",
    content: "Your subscription has been renewed successfully. Thank you for continuing to use our services. Explore the new benefits included in your plan.",
    type: "system",
    time: "2024-12-07T10:00:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "39",
    title: "Custom Alert",
    content: "Your profile was updated successfully. Ensure that your new details are accurate for a seamless experience. Visit your profile settings for further changes.",
    type: "custom",
    time: "2024-12-05T19:00:00",
    priority: "Low",
    isRead: true,
  },
  {
    id: "40",
    title: "Reminder",
    content: "The end-of-year party RSVP deadline is approaching. Confirm your attendance to secure your spot. Let’s celebrate our achievements together!",
    type: "reminder",
    time: "2024-12-01T20:00:00",
    priority: "Medium",
    isRead: false,
  },
];

  